name: watch_and_show
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  youtube_player_flutter: ^8.1.0
  iso_duration_parser: ^1.1.1


  #stateManagement
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  shared_preferences: ^2.0.15

  http: ^0.13.4




dev_dependencies:


  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
